if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_page-content',
		'title' => 'Page Content',
		'fields' => array (
			array (
				'key' => 'field_5588232cae25e',
				'label' => 'Type',
				'name' => 'template',
				'type' => 'select',
				'choices' => array (
					'Default' => 'Default',
					'Client' => 'Client',
					'Product' => 'Product',
					'Resource' => 'Resource',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5579f095b0d41',
				'label' => 'Headline',
				'name' => 'headline',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_558826f730b14',
				'label' => 'Related Links',
				'name' => 'related_links',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5588271346d13',
						'label' => 'Page',
						'name' => 'page',
						'type' => 'post_object',
						'column_width' => '',
						'post_type' => array (
							0 => 'all',
						),
						'taxonomy' => array (
							0 => 'all',
						),
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_5574c9907835c',
				'label' => 'Content Block',
				'name' => 'content_block',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Content With Links',
						'name' => 'content_with_links',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_55774abe0a581',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_55774adb0a582',
								'label' => 'Link List',
								'name' => 'link_list',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_55774b0a0a583',
										'label' => 'Page',
										'name' => 'page',
										'type' => 'post_object',
										'column_width' => '',
										'post_type' => array (
											0 => 'all',
										),
										'taxonomy' => array (
											0 => 'all',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_55774b4d0a584',
										'label' => 'Icon Class',
										'name' => 'icon_class',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5580664ad21c5',
										'label' => 'Heading',
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
						),
					),
					array (
						'label' => 'Content',
						'name' => 'content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_558979e135705',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Content With Pie Chart',
						'name' => 'content_with_pie',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5582b76296401',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_5582b76296402',
								'label' => 'Chart Info',
								'name' => 'chart',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5582b76296403',
										'label' => 'Total',
										'name' => 'total',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5582b76296404',
										'label' => 'Slices',
										'name' => 'slices',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_5582b7f396406',
												'label' => 'Value',
												'name' => 'value',
												'type' => 'number',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'min' => '',
												'max' => '',
												'step' => '',
											),
											array (
												'key' => 'field_5582b80a96407',
												'label' => 'Label',
												'name' => 'label',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_5582b81096408',
												'label' => 'Caption',
												'name' => 'caption',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
											array (
												'key' => 'field_5582b83996409',
												'label' => 'Color',
												'name' => 'color',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'row',
										'button_label' => 'Add Slice',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
						),
					),
					array (
						'label' => '2 Column Content',
						'name' => '2_column_content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_557e41a79191a',
								'label' => 'Column 1',
								'name' => 'column_1',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_557e41be9191b',
								'label' => 'Column 2',
								'name' => 'column_2',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Full Width Content',
						'name' => 'full_width_content',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5574cadf3b987',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Accordion',
						'name' => 'accordion',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_557e4a6b10a5c',
								'label' => 'Heading',
								'name' => 'heading',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_557e49bc10a59',
								'label' => 'Slide',
								'name' => 'slide',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_557e4a4010a5a',
										'label' => 'Heading',
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_557e4a4e10a5b',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'full',
										'media_upload' => 'yes',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
						),
					),
					array (
						'label' => 'Rate Group',
						'name' => 'rate_group',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5578cb640d4a7',
								'label' => 'Heading',
								'name' => 'heading',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5578cb8f0d4a8',
								'label' => 'SubHeading',
								'name' => 'subheading',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5578cb9c0d4a9',
								'label' => 'Rates',
								'name' => '',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5578cbaf0d4aa',
										'label' => 'Balance',
										'name' => 'balance',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5578cbba0d4ab',
										'label' => 'Rate',
										'name' => 'rate',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5578cbc10d4ac',
										'label' => 'APY1',
										'name' => 'apy1',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
						),
					),
					array (
						'label' => 'Fees',
						'name' => 'fees',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5578cc070d4ae',
								'label' => 'Description',
								'name' => 'description',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5578cc1a0d4af',
								'label' => 'Charge',
								'name' => 'charge',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Content Slider',
						'name' => 'content_slider',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_557e420f86c91',
								'label' => 'slides',
								'name' => 'slides',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_557e425486c92',
										'label' => 'Photo',
										'name' => 'photo',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_557e426d86c93',
										'label' => 'Heading',
										'name' => 'heading',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_557e428186c94',
										'label' => 'Content',
										'name' => 'content',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'br',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_558a8f2559b00',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'Gallery' => 'Gallery',
									'Testimonial Slider' => 'Testimonial Slider',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
					),
				),
				'min' => '',
				'max' => '',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
}
